# Utiliser l'image officielle de PostGIS
FROM postgis/postgis:latest

# Exposer les ports PostgreSQL
EXPOSE 5432

# Définir les variables d'environnement pour PostgreSQL
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase